### ISSUE TITLE
[GCP] Expose configuration for GCP Cloud NAT manual external IP address

### ISSUE THREAD

**Issue by champoeva** [gardener/gardener-extension-provider-gcp#1]
As mentioned in the google documentation https://cloud.google.com/nat/docs/using-nat#update_nat, there is a way to set a reserved static IP address for Cloud NAT. Currently gardener doesnt' have a configuration available for setting it to be manual instead of automatic. The reason for requesting this configuration is that we have an use case which requires us to whitelist our clusters' public IP addresses in different places, that don't allow access unless the IP address is officially whitelisted.

**Comment by vpnachev** [comment]
>  but we could also support setting the nat_ip_allocate_option to MANUAL_ONLY and when no ip address is specified we could create one manual and assign it to the cloud nat. 

I believe this is error prone:
* The service account will need explicitly privileges to manage this resource.
* Also, the shoot cluster provisioning can fail too late because of insufficient quota.
* Sometimes a single egress IP is not enough to handle all parallel connections, which will result in dropped packets.
* I do not see any advantage compared to the `AUTO_ONLY`.

**Comment by champoeva** [comment]
Hello, is there any update on this issue? The requested option for a reserved static ip is very important for our project, we are currently holding off on making all of the whitelist requests that we need, because of the uncertainty surrounding this issue. Could you please give us an estimate of when can we expect to have any type of solution or a workaround?

**Comment by mikosa** [comment]
We also need this feature to be available in GCP. Hope somebody can provide a timeline on this

**Comment by DockToFuture** [comment]
Started working on this.
