### ISSUE TITLE
GCP: Control the default allow-external-access FW rules

### ISSUE THREAD

**Issue by georgi-lozev** [gardener/gardener-extension-provider-gcp#4]
We have Gardener shoot clusters running in GCP with firewall rules like the following.

```
shoot-prod-allow-external-access
Ingress
Apply to all    
IP ranges: 0.0.0.0/0
tcp:80,443
Allow
1000
```

The fact that the port 80 is open to the internet is being classified as a high security risk.
There is nothing from our services actually listening on that port and it will be good if we could close it. 

Is there a way for you to allow us to have control over that configuration and open it only if needed?

**Comment by georgi-lozev** [comment]
Any updates on this one ?

**Comment by DockToFuture** [comment]
Will remove it today from `gardenctl` and create a separate rule for ssh access. Sry for the delay.

**Comment by MichaelSp** [comment]
I'm getting mails complaining about this FW rule. Any update on the future plans?

**Comment by avizov** [comment]
We are facing the same and getting a weekly alert mail from Minerva that complaining about the Firewall rule shoot. 
When is it planned to be fixed?

**Comment by vlerenc** [comment]
@ScheererJ @DockToFuture Could you please help here? Minerva (formerly Prisma) complains (in all stakeholder accounts): https://wiki.wdf.sap.corp/wiki/display/itsec/Google+Cloud+-+Hardening#GoogleCloudHardening-6.1.3FirewallRulesforInfrastructureports

Since only TLS traffic is permitted, can we drop port 80 for this default firewall configuration?
